/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projectdatabases;

/**
 *
 * @author nelssalminen
 */
public class MainFrame extends javax.swing.JFrame {

    // Creates an instance of this class, with this you can call every method/variable in here
    // without using statics
    static MainFrame mainFrame = new MainFrame();
    
    // Call MainFrame.mainFrame.mainMenu.<random method> to use a method from the MainPanel panel, no need for 
    // static variables
    MainPanel mainMenu = new MainPanel();
    
    // Call MainFrame.mainFrame.playerMenu.<random method> to use a method from the ContestantPanel panel, no need for 
    // static variables
    ContestantPanel playerMenu = new ContestantPanel();
    
    // Call MainFrame.mainFrame.toernooiMenu.<random method> to use a method from the TournamentPanel panel, no need for 
    // static variables
    TournamentPanel toernooiMenu = new TournamentPanel();
    
    // Call MainFrame.mainFrame.masterclassMenu.<random method> to use a method from the MasterclassPanel panel, no need for 
    // static variables
    MasterclassPanel masterclassMenu = new MasterclassPanel();
    
    // Call MainFrame.mainFrame.adjustMenu.<random method> to use a method from the EditContestantsPanel panel, no need for 
    // static variables
    EditContestantsPanel adjustMenu = new EditContestantsPanel();
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        // Sets the screen to the main menu
        this.setContentPane(mainMenu);
        
        // Centers screen location on monitor
        this.setLocationRelativeTo(null);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                mainFrame.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
